"""Geracao da secao de explicabilidade (explainability) da resposta.
"""

from __future__ import annotations

from . import config
from .state import EstadoAssistente


def montar_secao_explicabilidade(estado: EstadoAssistente) -> str:
    dp = estado["dados_paciente"]

    campos_usados = []
    if dp.get("sintomas"):
        campos_usados.append(f"symptoms: {', '.join(dp['sintomas'])}")
    if dp.get("historico_relevante"):
        campos_usados.append(f"history: {dp['historico_relevante']}")
    if dp.get("exames_pendentes"):
        campos_usados.append(f"pending exams: {', '.join(dp['exames_pendentes'])}")
    if dp.get("resultados_recentes"):
        campos_usados.append(f"recent results: {dp['resultados_recentes']}")
    if dp.get("ultima_atualizacao"):
        campos_usados.append(f"medical record updated in: {dp['ultima_atualizacao']}")

    if campos_usados:
        atribuicao = "Based on the following patient data: " + "; ".join(campos_usados) + "."
    else:
        atribuicao = "No structured patient data was available for this response."

    transparencia = (
        f"\n\n[Generated by {config.ROTULO_MODELO}. "
        f"This is not a licensed physician and does not replace clinical judgment; "
        f"recommendations require human validation.]"
    )

    return f"\n\n{atribuicao}{transparencia}"
